### PR TITLE
Show ERC info only if erc-track minor mode on.

### PR DESCRIPTION
**Pull request by punchagan**
`erc-track-minor-mode' can be disabled at any time, but this does not
unset the erc-modified-channels-object. The object is used if the minor
mode is enable again.

### CODE REVIEW

**Comment by milkypostman** [comment]
if `erc-track-minor-mode` is enabled is it safe to assume that the variable is defined?

**Comment by punchagan** [comment]
Yes, it has a `(defvar erc-modified-channels-alist nil "...")`.  Should I change the check to `(and (boundp 'erc-track-minor-mode) erc-track-minor-mode)`

**Comment by punchagan** [comment]
I changed the check to `(and (boundp 'erc-track-minor-mode) erc-track-minor-mode)`.

**Comment by milkypostman** [comment]
ok cool. that's fine. I was thinking we don't need to check that it's bound? because by default won't it be nil?

**Comment by milkypostman** [comment]
nvm, my elisp is getting weak from lack of use :)

**Comment by punchagan** [comment]
Thanks for merging!  :)

**Comment by milkypostman** [comment]
thakns for the PR

**Pull request merged**
