### PR TITLE
powerline-vc: same vcs display in tty and gui emacs, using the UTF-8 'branch' char and the more compact and informative vc-mode variable

### PR DESCRIPTION
**Pull request by deb0ch**
See issue  #123

### CODE REVIEW

**Comment by milkypostman** [comment]
sorry i didn't ask this sooner. but will this work with any font?

**Comment by deb0ch** [comment]
I did not add anything, just been reusing the font that was already being used in tty.

**Comment by milkypostman** [comment]
my concern is that some fonts may not support the git character. the concession was that TTY would use the branch characters. but in GUI, i'm concerned some fonts might not support it and then you won't be able to see the character. 

i'll merge and see if people complain.

**Comment by deb0ch** [comment]
Worst case scenario, just an if statement to hide it in GUI.

The main thing is to not have that extra-long full SHA1 that take all the space in TTY anymore and have that nice extra bit of info about your vcs =)

Happy it got merged, cheers !

**Pull request merged**
