### PR TITLE
utf-8 terminal support (patched fonts required), as requested

### PR DESCRIPTION
**Pull request by unic0rn**
minor modes disabled - yeah, i know, it's a matter of taste - but it was too much crap being displayed, imho.

### CODE REVIEW

**Comment by milkypostman** [comment]
OK, I see from our previous conversation the confusion and why I was confused about this patch.

So there are two use cases.

1. You use patched fonts in GUI mode and want to use unicode characters for you modeline.
2. You use the terminal with patched fonts and want to use unicode characters for your modeline.

To solve 1, we need to have a separator that uses ut8.

To solve 2, we need to *always* fallback to the utf8 separator when we are in non-window mode.

I will have to modify the patchset but will take a day and do this soon.

**Comment by unic0rn** [comment]
both solutions you've mentioned are in this patch i think, or i'm confused.
there is a utf-8 separator defined, and it is used as a default in non-GUI mode.

so both use cases should work as supposed - well, second one obviously works, by default, and first one will if one changes the default to utf-8. there may be a change required for the repo branch character, that's displayed only in non-GUI mode i guess.

but then, perhaps we're doing it wrong. patched fonts guarantee better 'visual compatibility' with the original vim version, so perhaps it would be better to have 2 branches - one using icons in GUI emacs with xpm support, and another one requiring patched fonts for all use cases and ditching bitmaps entirely, in different repos. it would clean-up things a little bit. exchanging patches could be problematic then, but there not much progress on that front currently anyway, so it's hardly an issue.

**Comment by milkypostman** [comment]
The patch is almost there. But you don't want to have the distinguished be
the defcustom statement because that only gets executed when loading the
file. You actually want to check in the modeline itself for whether to
fallback to UTF8. I'll ping you when I put this together to have a look and
see what you think.

Right now this code is a slow moving beast.

**Comment by unic0rn** [comment]
i guess that covers the 'always fallback' part.

but see, that's what i'm getting at with the split scenario - what do you think about it? leaving the main repo as it is and throwing out all xpm stuff from my fork, effectively changing it into patched-fonts-only version?

wouldn't that be overall simpler to handle?

**Comment by milkypostman** [comment]
it would but i don't think you can do the *fallback* in that case. because
how will you know when to use what package. there would be conflicts for
sure; at least for the normal user. I actually think a fallback option in
the current version is quite easily doable. When I get a chance to put in
my changes you can have a look at my PR before I submit it and make some
comments, or try it.

**Comment by unic0rn** [comment]
no, i guess you misunderstood. what i meant are two separate branches - yours and mine - with different backends, so to speak. yours would stay as it is, with xpm stuff, mine would deal with patched fonts only - no fallback, all xpm code removed. it would work under terminal and under GUI, as long as patched font would be used - which would be simply required, period.

**Comment by milkypostman** [comment]
Yeah but how do I configure my modeline to be used with both at the same
time?

**Comment by unic0rn** [comment]
you don't. it gets down to 2 scenarios:
 - user doesn't want to use patched fonts, so the powerline will work only under GUI emacs with xpm support - which is the case for your branch now
- user wants to use patched fonts, so the powerline will work under both GUI emacs and under terminal, as long as patched fonts are in use.

i don't think someone would like to use patched fonts under the terminal and at the same time, xpm version in case of GUI - simply because patched fonts offer more special characters and scale better, and the user is likely to use the same font in emacs and in the terminal anyway.

if someone would like to do that though, single check if one is in a GUI or not in .emacs.el and loading correct powerline version would do the trick. i just honestly see no point in doing so.

**Comment by milkypostman** [comment]
I don't think splitting things up is a good idea really. Well, mainly
because i don't think there is an issue here with keeping them combined.
Let me make the changes then we can see if it's really worth it or not.

**Comment by milkypostman** [comment]
@unic0rn please look at 91fe2bd3d0941ab2470b473128d100be79d5bf1b and 375e172fc9c39963b6514f07b6674325b8393f56

See if this works for you. The only things I didn't get to was your other fancy stuff.

**Comment by milkypostman** [comment]
and now i added bdd98eb8bc0799bc1260d80c99fecd48d982575b

so this should be all caught up except for your minor mode disabled change. Think we need a `defcustom` for that. let me know what you think.

**Comment by unic0rn** [comment]
as far as quick test goes, it seems to work - under the terminal, at least, can't test it under GUI.

still, i guess we disagree on the future of this. it's great that you've backported those changes to your branch and that you did it properly. in the long run though, i see the issue with keeping things combined - it's overcomplicating stuff. when i'll get more free time, i'll remove all xpm stuff from my branch, simplifying it as much as possible.

don't get me wrong, there's certainly a point to your version - not everyone wants to use patched fonts. for those that do want though, everything else than utf-8 support is completely pointless.

**Comment by milkypostman** [comment]
I guess I don't understand your concern here. The only real issue is the
pxm generation for the gui separators. And for all intensive purposes you
can ignore them. Are you concerned about the workflow of having to submit
PRs? I'm happy to have you as a committer.

Just don't clearly see what is to be gained. I mean I don't use this so I
am not invested in it, but I see it more from the community perspective
that it seems odd to have TWO packages when there is so much overlap.

I feel this way about git-gutter. There are like four different packages,
one for terminal and one for fringe and I don't understand why I need to
think about this. Why can't the packages just behave differently for me.

Anyways. You seem very stuck on this idea and this is what open source is
about, but my fear is in diverging users are the ones who will suffer.

**Comment by unic0rn** [comment]
maybe i'm just an 'extremist' when it comes to code simplification.

patched fonts look better, provide more symbols out of the box as for now, and work under terminals - so that's the way to go, imho. i would just ditch the xpms altogether, instead of having to deal with 'can haz repo branch/line number symbols as xpm icons plz' requests later.

also, i wouldn't risk saying that everyone would be willing to use patched fonts if given no choice, but displays these days are getting higher and higher dpi. even with throwing font antialiasing aside, how do those xpms scale? at my 1280x1024 17" screen, 14pt ubuntu mono is the smallest thing i can work with - i wear glasses, very weak ones but anything smaller than that font is just something i can't stand in the long run. and i imagine that with 2k and even 4k monitors getting more and more popular, more and more users will expect a pixel fidelity only a vector font can provide.

so what's to be gained is visual quality and code simplification, at the expense of requiring patched fonts. perhaps i'm wrong in this regard, but i would like to see a comparison of powerline using patched font and xpms, at some not-too-small font size.

i understand your point of view, you want the users to have a choice. i guess i don't have a problem with stripping them of one that in time will be most likely deprecated anyway.

**Comment by milkypostman** [comment]
I'm not sure how fonts work but my understanding is that they need things
like aliasing and such because they are imprecise. Xpms will scale
indefinitely because they are pixel based, essentially vector drawn, based
on the actual resolution (this is actually one of the things I added when I
made this versions).

But that's really irrelevant to the discussion. There is almost no code
complexity outside of the xpm generation. That is only complicated because
I was being overly clever and trying to see if I fully understood macros. I
think you will see that once you stop out xpm and the memoize functions
almost all the code remains intact.

**Comment by jasonm23** [comment]
Very true,  divergence is a headache.  The package can relatively easily accommodate all functionality.

Donald's example of git-gutter is poignant, it's a perfect case of divergence serving no purpose whatsoever. There should be a single package which simply *works*.

By the way Donald, the phrase you're after is:

> To all intents and purposes.

Just one of those strange idiomatic English phrases. ;)

**Comment by osxi** [comment]
I use @unic0rn's fork in the terminal and just recently switched to GUI and it works just the same.

@milkypostman I had some grief from git-gutter about the linum and/or terminal emacs but somehow- and it happened by luck, I guess- it now works exactly how you'd think in both terminal and gui with or without linum on.

**Comment by unic0rn** [comment]
@milkypostman i guess i misunderstood xpms a bit then. and you misunderstand antialiasing imho, everything that lacks 8bit alpha channel can be considered imprecise, besides, there are antialiasing techniques like cleartype that require knowledge of the subpixel arrangement on the screen, so bitmaps cannot use it.

@jasonm23 perhaps it is. not more than a lack of active maintainer working on his project. milkypostman dropped by and ported my changes - and kudos to him for doing that and taking time to discuss it all - but at the same time, i know exactly how it feels not to have time to work on pieces of your own released code, for the community. it's a headache for both sides.

also, don't think i'm trying to enforce some split or something here - far from that. i was interested if milkypostman will share my view of the future of this project - he doesn't, and that's fine. i'll do my thing as i did before, and as many other people do - my fork was created for my personal purposes - i've released it so that maybe someone will find it useful, but i never expected that much of a feedback, and i was surprised when people started forking it and tweaking it.

and it all ended up being merged here, which is great. i'll just keep tinkering with my fork in some free time, and when i'll add something useful/nice - PR will show up here and hopefully merging it won't be too painful.

**Comment by milkypostman** [comment]
@unic0rn so would there be any issue with just working directly in this branch then and leaving the xpm stuff but focusing on the utf-8 stuff? I'm happy to make the xpm stuff a second-class citizen but I don't feel like we should ditch it completely. And, as you said, it is much better to have someone who is supporting the project. To me it's really not a big deal to focus on the utf-8 parts.

@jasonm23 hahaha. That's hilarious! I feel dumb, but also am curious if it still works the other way? I mean, *intensive* purposes should **really** matter the most right? :)

**Comment by jasonm23** [comment]
This package has been in need of a maintainer for a long time.

If you have time and energy to put into the fork.  We should be talking about you simply looking after the package.

I know of no one else who is up for it.

Is this something you would like to do?

**Comment by jasonm23** [comment]
@milkypostman I know rite?! It totally should make sense!  (But no don't do it! ;)

**Comment by unic0rn** [comment]
@milkypostman my emacs lisp skills aren't my forte, but at least i can avoid breaking things i guess ;) i can code stuff, as can be seen by my other repos, i just never bothered to deal with emacs lisp more than i needed for my own purposes, like with this whole utf-8 stuff.

do i have ideas? sure. make the whole thing look more 'powerline-y' if possible, perhaps include some stuff that would get automatically enabled when some package is detected as being in use, like emms - instead of relying on 'this or that should support powerline'. those are just raw ideas that would have to be tested if they're even valid, so if it's a fork or a separate branch in the main repo, that's more of a technicality.

so while i can do my best, i just cannot guarantee the timeline. i certainly have the energy for many things, but time is entirely different matter. and as for handling issues/PRs, you certainly know your own code better - and it doesn't seem like you're entirely 'outta here', either :P sure, i can handle it, but then there's the question if i'll be able to find time to do so.

wanna make me a collaborator to speed up merging my ideas when i'll have time to work on them - go ahead, just don't count me in as a maintainer, at least not yet.

and if you would prefer to keep the more experimental stuff in this repo, just on a separate branch, i have no problem with that - i can ditch my fork, together with the ideas of throwing the xpm stuff out of a window, but you're right that i would rather focus on utf-8 stuff, treating xpm as a second-class citizen. i'm just not using GUI version of emacs at all.

**Comment by milkypostman** [comment]
whatever is fine with me. you're a collaborator. do whatever you can find time for and no worries. if you want me to look at something before it goes to master, just send a PR. otherwise I trust that you will do what is best and I'm fine with utf-8 being the primary driver for this package.

**Comment by unic0rn** [comment]
will do.
when i'll start working on something, i'll shutdown my fork and push the results to a separate branch here.

thanks.

**Pull request closed without merging**
